# sonar-project.properties
sonar.projectKey=food-booking-app
sonar.projectName=Food Booking Application
sonar.projectVersion=1.0

# Tell Sonar where the source code is
sonar.sources=backend,frontend

# Ignore the virtual environment or tests for the actual code analysis
sonar.exclusions=backend/test_*.py,**/__pycache__/**

# Tell Sonar where to find the Python coverage report we just generated
sonar.python.coverage.reportPaths=backend/coverage.xml

# Tell Docker to route this to your Windows host machine!
sonar.host.url=http://192.168.56.1:9000